export const SET_SESSION = 'SET_SESSION';
export const SET_CREDENTIALS_ERROR = 'SET_CREDENTIALS_ERROR';
export const EMPTY_CREDENTIALS_ERROR = 'EMPTY_CREDENTIALS_ERROR';
export const SET_USER = 'SET_USER';
